import type { Metadata } from "next";
import { Electrolize } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import ScrollToTop from "./utils/ScrollToTop";

const sedgewick = Electrolize({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#FF0066" /> {/* Set theme color */}
      </head>
      <body
        className={`${sedgewick.className} antialiased bg-[#f5f5ff] text-black dark:bg-[#202938] dark:text-white`}
      >
        <Suspense>
          <ScrollToTop>{children}</ScrollToTop>
        </Suspense>
      </body>
    </html>
  );
}
